branch-defaults:
  main:
    environment: orgaworks-dev
  orgacommit-1:
    environment: orgaworks-dev
    group_suffix: null
global:
  application_name: orgaworks
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
