# Generated by Django 3.0.14 on 2022-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Exotics', 'Exotics'), ('vegetables', 'Vegetables')], max_length=20)),
                ('productlinkImage', models.ImageField(upload_to='products')),
                ('lowest_prices', models.TextField(max_length=10)),
                ('communityfarm', models.CharField(max_length=10000)),
                ('greendna', models.CharField(max_length=10000)),
                ('healthybuddha', models.CharField(max_length=10000)),
                ('organiceraa', models.CharField(max_length=10000)),
                ('freshfarm', models.CharField(max_length=10000)),
            ],
        ),
    ]
