# Generated by Django 3.0.14 on 2022-07-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
