# Generated by Django 3.0.14 on 2022-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0004_auto_20220701_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewProduct',
        ),
    ]
