# Generated by Django 3.0.14 on 2022-07-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0006_auto_20220701_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewproduct',
            old_name='email',
            new_name='emailId',
        ),
    ]
