# Generated by Django 3.0.14 on 2022-07-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0007_auto_20220701_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewproduct',
            old_name='comment',
            new_name='commentReview',
        ),
    ]
