# Generated by Django 3.0.14 on 2022-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0008_auto_20220701_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewproduct',
            name='rate',
        ),
    ]
