# Generated by Django 3.0.14 on 2022-07-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0009_remove_reviewproduct_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('blogImage', models.ImageField(upload_to='blogs')),
                ('content', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
