# Generated by Django 4.0.4 on 2022-07-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=10000000)),
                ('product', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewProduct',
        ),
    ]
