# Generated by Django 4.0.4 on 2022-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0011_review_delete_reviewproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('Role', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Linkedin', models.CharField(max_length=300)),
                ('Employeeid', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='Resumes')),
                ('Employee_Status', models.CharField(default='Not Approved', max_length=100)),
            ],
        ),
    ]
